### ISSUE TITLE
AttributeError: module 'cv2.detail' has no attribute 'WAVE_CORRECT_AUTO'

### ISSUE THREAD

**Issue by giacomomarchioro** [OpenStitching/stitching#112]
Hi,
With largestinteriorrectangle-0.2.0 stitching-0.4.0 I have got this error:

AttributeError: module 'cv2.detail' has no attribute 'WAVE_CORRECT_AUTO'

**Comment by lukasalexanderweber** [comment]
Yeah we know that: https://github.com/OpenStitching/stitching/discussions/101

But the error message could be better..
