### ISSUE TITLE
problem with largest joint interior rectangle in Cropper class

### ISSUE THREAD

**Issue by ChanifRusydi** [OpenStitching/stitching#115]
At first, im trying using the Stitcher class normally like this
`import stitching
from stitching import Stitcher

settings = {"detector": "akaze", "confidence_threshold": 0.2, "warper_type":"plane"}
stitcher = Stitcher(**settings)
stitcher = stitching.Stitcher()
panorama = stitcher.stitch(["image1_60_left.jpg", "image1_60_right.jpg"])`
but then I noticed it took abnormally long time to finish (let them running for like 5 minutes).  When I'm doing similar thing using [stitching_detailed.py by opencv[](https://raw.githubusercontent.com/opencv/opencv/4.x/samples/python/stitching_detailed.py) it only took at most 3 sec. I decided to look at the error message and dive into Stitching_Tutorial.ipynb and found out that 'cropper.estimate_largest_interior_rectangle(mask)' is the one who caused it.

![Screenshot 2023-07-24 011830](https://github.com/OpenStitching/stitching/assets/62838892/ab490a84-845b-41c4-8f52-14e703920cec)

As of right now, idk about the thing further from here. And here is the image I use

![image1_60_left](https://github.com/OpenStitching/stitching/assets/62838892/4f615d8b-bec6-45b0-9f11-5a19c343e805)
![image1_60_right](https://github.com/OpenStitching/stitching/assets/62838892/b68c4e63-b971-426d-a418-03b7eb960cca)

**Comment by lukasalexanderweber** [comment]
Which operating system are you on?

**Comment by lukasalexanderweber** [comment]
You can get the same result as stitching_detailed by setting crop to false

**Comment by lukasalexanderweber** [comment]
And can you please share the Error Message?

**Comment by lukasalexanderweber** [comment]
it shouldn't reach `import largestinteriorrectangle` if crop is set to False. See https://github.com/OpenStitching/stitching/blob/main/stitching/cropper.py#L54. Can you debug and check why it reaches this part of the code?

**Comment by lukasalexanderweber** [comment]
Any updates on this?

**Comment by ChanifRusydi** [comment]
Sorry to keep you waiting, for now I cant give you updates on this.  I guess I could give you updates tomorrow

**Comment by lukasalexanderweber** [comment]
I moved it into the stitching package so we only have one place for issues
