### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by Justin-ShanJ** [OpenStitching/stitching#118]
just run the given [Jupyter Notebook] and imgs, but it show an error in **Subset**: TypeError: only integer scalar arrays can be converted to a scalar index. How to solve it?

![1688151181948](https://github.com/OpenStitching/stitching_tutorial/assets/87164306/094afecb-6291-43b9-a421-5a7e443bd9a1)

**Comment by lukasalexanderweber** [comment]
continued in https://github.com/OpenStitching/stitching/issues/40
