### ISSUE TITLE
image_handler() is missing. 

### ISSUE THREAD

**Issue by cyhsu** [OpenStitching/stitching#133]
Hi, 

I tried to follow the tutorial to resize the images using `image_handler()`; however, it looks like it is missing. I went back to the closed issues and found this class function was addressed at #53  on Mar 02. 

[image_handler](https://github.com/lukasalexanderweber/stitching/blob/main/stitching/image_handler.py), but when I clicked it, it shows 404. 

Any idea why it is disappeared.

**Comment by lukasalexanderweber** [comment]
The Image_handler class was replaced by the Images class in https://github.com/OpenStitching/stitching/releases/tag/v0.5.0.

The Tutorial was updated for this Changes

**Comment by cyhsu** [comment]
Thank you!
