### ISSUE TITLE
Manually enforce image matches and stitching sequence

### ISSUE THREAD

**Issue by evan-wes** [OpenStitching/stitching#144]
Say I have an NxM 2D grid of images, so that I know for sure which pairs of images have overlap and should be matched together. The automatic matching process fails if, for example, images at opposite sides of the grid have similar features. How can I modify the code to manually enforce which images are matched together?

**Comment by lukasalexanderweber** [comment]
See https://github.com/OpenStitching/stitching/discussions/138

**Comment by lukasalexanderweber** [comment]
You can also subset the matrix in smaller subsets

**Comment by lukasalexanderweber** [comment]
You could just remove the last features/matches/images as its done here https://github.com/OpenStitching/stitching/blob/54d5f8e23491c3786bc7e1294dd233015dd56c12/stitching/stitcher.py#L147 (keep all indices but the last)
