### ISSUE TITLE
Regarding calculation of Homography matrix 

### ISSUE THREAD

**Issue by Ram-198** [OpenStitching/stitching#170]
Hi,

Currently, i have 2 image (lets say A and B) and i am using SIFT and BestOf2NearestMatcher() for feature detection and matching _(**And i am planning to use my own feature matching method in the future my school project**, i need help for H matrix estimation similar to OpenCV)._

the output _**pairwise_matches**_ in file **feature_matcher.py** (code snippet below)

pairwise_matches = self.matcher.apply2(features, *args, **kwargs)

pairwise_matches is of size 4 with datatype _**detail_MatchesInfo**_ where, index [1] and [2] contains valid H matrix for image A & B respectively.

So, could any one please provide more details on how exactly **_homography [2]_** is generated??

i think following is the high level  flow of  _BestOf2NearestMatcher_  _**(but i want to know more details on Homography is estimated for  image B)**_

_BestOf2NearestMatcher::match()
  |
  |- CpuMatcher::operator()
  | |
  | |- CpuMatcher::match()
  | |
  | |- FlannBasedMatcher::knnMatch()
  |
  |- (Convert the matched points to coordinates whose center is zero)
  |
  |- findHomography()
  |
  |- (Check the results and decide whether to press “No” and calculate again)
  |
  |- findHomography() (executed only in inliers)_
  
  
  **in particular, how matches between image B and A are extracted and how its used for estimating the Homography matrix .??**
  
  Thank you in advance.

**Comment by lukasalexanderweber** [comment]
You can search for the code how the matrix is calculated within https://github.com/opencv/opencv/
