### ISSUE TITLE
 Camera parameters adjusting failed.

### ISSUE THREAD

**Issue by Tickets14** [OpenStitching/stitching#178]
How do you fix this error?
```
from stitching import Stitcher
import cv2

stitcher = Stitcher(detector="sift", confidence_threshold=0.2)
panorama = stitcher.stitch([cv2.imread("receipt\mercadona_1.jpg"), cv2.imread("receipt\mercadona_2.jpg")])


cv2.imwrite("panorama.jpg", panorama)
```

Error:      raise StitchingError("Camera parameters adjusting failed.")
stitching.stitching_error.StitchingError: Camera parameters adjusting failed.

here the image i used:
![mercadona_1](https://github.com/OpenStitching/stitching/assets/53848311/bd97af8b-afc2-49ad-b178-54f923507b7d)
![mercadona_2](https://github.com/OpenStitching/stitching/assets/53848311/6e643327-4b2e-4079-8d17-e3ab51c203f8)

**Comment by lukasalexanderweber** [comment]
You need to use AffineStitcher

**Comment by Tickets14** [comment]
I tried to use AffineStitcher but i got an error:

```
    raise StitchingError(
stitching.stitching_error.StitchingError: No match exceeds the given confidence threshold.
                                 Do your images have enough overlap and common
                                 features? If yes, you might want to lower the
                                 'confidence_threshold' or try another
                                 'detector'.
```

**Comment by HDareYR** [comment]
The code seems cant been able to find enough matches 。try another two images or  modify some parameters about matches finding maybe。 by the why ,could you tell me how to learn more about the lib of Stitching? waiting for your  reply.thanks

**Comment by lukasalexanderweber** [comment]
the best thing you could do is to use the verbose mode (`-v`) to see where the problems are
