### ISSUE TITLE
"Segmentation fault" error

### ISSUE THREAD

**Issue by mariiak2021** [OpenStitching/stitching#184]
Hi @lukasalexanderweber 

Thank you for the great work!
I'm having some troubles with the algorithm since yesterday and though you might provide some information.
While using stitching pipeline I'm getting error: "Segmentation fault" without any further explanation. It is not "Stitching error" and happening sometime during cropping by my tests, although I can't get precise place or understand what could cause the error. I haven't done any changes to my code since yesterday.
Will appreciate any ideas!

Best,
Mariia

**Comment by mariiak2021** [comment]
I read some other errors with cropping. Should add that I'm running code on remote Linux server

**Comment by lukasalexanderweber** [comment]
What do you mean with " I read some other errors with cropping. "

**Comment by mariiak2021** [comment]
@lukasalexanderweber I mean other issues like https://github.com/OpenStitching/stitching/issues/119

**Comment by lukasalexanderweber** [comment]
Quite sure this isn't related to the stitching package: https://stackoverflow.com/questions/2346806/what-is-a-segmentation-fault

**Comment by mariiak2021** [comment]
Hi @lukasalexanderweber you are right - I've solved segmentation error but still getting errors: free(): invalid size or munmap_chunk(): invalid pointer. Have no idea how to solve them. Can't make even one stitching.

**Comment by lukasalexanderweber** [comment]
This is also really C++ specific: https://stackoverflow.com/questions/32118545/munmap-chunk-invalid-pointer.

Don't you have a way to test it locally and make sure your installation on the remote server is correct

**Comment by mariiak2021** [comment]
Closing as the problem was solved!
