### ISSUE TITLE
Can only horizontal image reconstruction be performed? Can a panoramic 360 view image similar to the one below be generated?

### ISSUE THREAD

**Issue by libai-lab** [OpenStitching/stitching#231]
![room](https://github.com/user-attachments/assets/38cb6e16-2fdd-462a-a6e3-a11d233b6db3)

**Comment by lukasalexanderweber** [comment]
This is discussed e.g. in https://github.com/OpenStitching/stitching/discussions/79. I had some promising intermediate results but not a final sollution
