### ISSUE TITLE
CLI --affine parameter has no effect

### ISSUE THREAD

**Issue by mstenta** [OpenStitching/stitching#243]
It seems that the `--affine` CLI parameter is not working as expected.

## Expected behavior

According to the CLI help text for the `--affine` parameter:

`Overwrites multiple parameters to optimize the stitching for scans and images captured by specialized devices.`

The [tutorial](https://github.com/OpenStitching/stitching_tutorial/blob/master/docs/Stitching%20Tutorial.md#affine-stitcher) specifically outlines the parameters that should be overridden:

```
{'estimator': 'affine', 'wave_correct_kind': 'no', 'matcher_type': 'affine', 'adjuster': 'affine', 'warper_type': 'affine', 'compensator': 'no'}
```

## Actual behavior

The CLI script does not explicitly override those parameters when `--affine` is used, and it explicitly sets them to non-affine defaults.

For example, the `--matcher_type` CLI parameter sets `default=FeatureMatcher.DEFAULT_MATCHER,` which is `homography`.

https://github.com/OpenStitching/stitching/blob/a471af1a725d6525dcfe96436b27334a87bcd2bf/stitching/cli/stitch.py#L87

## Steps to reproduce

The following Docker commands (with any set of images) will create verbose output with `00_stitcher.txt` files that show the actual parameters that are used.

With `--affine`:

Command: `sudo docker run --rm -v ./:/data openstitching/stitch --affine --verbose ./*.jpg`

Result: `AffineStitcher(**{'medium_megapix': 0.6, 'detector': 'orb', 'nfeatures': 500, 'matcher_type': 'homography', 'range_width': -1, 'try_use_gpu': False, 'match_conf': None, 'confidence_threshold': 1, 'matches_graph_dot_file': None, 'estimator': 'homography', 'adjuster': 'ray', 'refinement_mask': 'xxxxx', 'wave_correct_kind': 'horiz', 'warper_type': 'spherical', 'low_megapix': 0.1, 'crop': True, 'compensator': 'gain_blocks', 'nr_feeds': 1, 'block_size': 32, 'finder': 'dp_color', 'final_megapix': -1, 'blender_type': 'multiband', 'blend_strength': 5, 'timelapse': 'no'})`

Without `--affine`:

Command: `sudo docker run --rm -v ./:/data openstitching/stitch --verbose ./*.jpg`

Result `00_stitcher.txt`:

`Stitcher(**{'medium_megapix': 0.6, 'detector': 'orb', 'nfeatures': 500, 'matcher_type': 'homography', 'range_width': -1, 'try_use_gpu': False, 'match_conf': None, 'confidence_threshold': 1, 'matches_graph_dot_file': None, 'estimator': 'homography', 'adjuster': 'ray', 'refinement_mask': 'xxxxx', 'wave_correct_kind': 'horiz', 'warper_type': 'spherical', 'low_megapix': 0.1, 'crop': True, 'compensator': 'gain_blocks', 'nr_feeds': 1, 'block_size': 32, 'finder': 'dp_color', 'final_megapix': -1, 'blender_type': 'multiband', 'blend_strength': 5, 'timelapse': 'no'})`

## Cause

This is happening because the `--affine` parameter only affects which class is used (`AffineStitcher()` instead of `Stitcher()`), but it does not explicitly override the parameters that are passed into `initialize_stitcher()`.

https://github.com/OpenStitching/stitching/blob/a471af1a725d6525dcfe96436b27334a87bcd2bf/stitching/cli/stitch.py#L318

## Solution

Perhaps before line 318 of `cli/stitch.py` all of the parameters that should be overridden for affine-mode can be reset to the appropriate values.

This would mean that if `--affine` is used, then the other parameters would have no effect (--`estimator`, `--wave_correct_kind`,  `--matcher_type`,  `--adjuster`, `--warper_type`, `--compensator`).

The other option is to still allow individual options to be overridden AFTER the `--affine` overrides are applied, but I feel like someone wants to do that they shouldn't use `--affine`.

## Workaround

For now, if you need the effects of `--affine`, those parameters can be explicitly set on the command line like so:

`--wave_correct_kind no --matcher_type affine --adjuster affine --warper_type affine --compensator no --estimator affine`

**Comment by lukasalexanderweber** [comment]
wow great catch and awesome issue with really much detail! 

That means using `--affine` mode in the cli was never working :(

I thought that the cli only have those arguments in the `args_dict` that are actually used by the user.

Anyway, even then if the user passes in `--affine --matcher_type homography` the `matcher_type` should automatically be overwritten with `affine` as you [shoud not mix the two models](https://docs.opencv.org/4.x/d8/d19/tutorial_stitcher.html)

> Certain detailed settings of [cv::Stitcher](https://docs.opencv.org/4.x/d2/d8d/classcv_1_1Stitcher.html) might not make sense. Especially you should not mix classes implementing affine model and classes implementing Homography model, as they work with different transformations.

**Comment by lukasalexanderweber** [comment]
This is the perfect explanation for https://github.com/OpenStitching/stitching/issues/125

**Comment by lukasalexanderweber** [comment]
closed with https://github.com/OpenStitching/stitching/commit/da14e4903e8ab6d63ba9a3f04a40283d0a156303
