### ISSUE TITLE
Exploring Blurriness in Image Stitching

### ISSUE THREAD

**Issue by ssfantasy2023** [OpenStitching/stitching#247]
My images have become blurred in certain areas after stitching. Could you please explain why this happens and which parameter can be adjusted to resolve it?

My settings parameters are as follows：
settings = {
    "detector": "sift",
    # "nfeatures": 1000,
    "confidence_threshold": 0.5,
    "crop": False,
    "estimator": "affine",
    "wave_correct_kind": "no",
    "matcher_type": "affine",
    "adjuster": "affine",
    "warper_type": "affine",
    "compensator": "no",
    "medium_megapix": 0.8,  # 0.5
    "low_megapix": 0.5,  # 0.1
    "final_megapix": -1,
    "range_width": -1,
    "nr_feeds": 1,
    "block_size": 32,
    "try_use_gpu": True,
    "blender_type": 'multiband',
    "blend_strength": 1,
}

![final_panorama_github](https://github.com/user-attachments/assets/fe678545-424b-423a-adaf-4beb1b9a3496)

**Comment by lukasalexanderweber** [comment]
Do you stitch all Images at once or sequentially like https://github.com/OpenStitching/stitching/issues/238?

**Comment by songbotao** [comment]
> Do you stitch all Images at once or sequentially like #238?

I am stitching them together in sequence because when I try to stitch all the images at once, OPEV runs into a memory error, similar to issue #238. However, it seems that this problem hasn't been resolved either.

**Comment by lukasalexanderweber** [comment]
closing this in favor of https://github.com/OpenStitching/stitching/issues/247
