### ISSUE TITLE
Heading of the pano

### ISSUE THREAD

**Issue by snowface3** [OpenStitching/stitching#72]
Hi,
Thank for making this tool, and sharing it with the public. I also commend your efforts to support the community for answering questions. I can imagine it takes a lot of effort. I'll try to keep my question brief:

I have visual odometry running, so I know the exact heading of each input frame. How can I find the heading of the panorama?

**Comment by lukasalexanderweber** [comment]
can you make a quick sketch with what you mean with heading? is your panorama creation successfull?

**Comment by lukasalexanderweber** [comment]
can't you just calculate it? 

in your example the panorama seems to cover 0°-100°. So the Pano heading could be 50°?

**Comment by lukasalexanderweber** [comment]
the matrices can be found in the `cameras` variable.

https://github.com/lukasalexanderweber/stitching/blob/main/stitching/stitcher.py#L95 (you can also check out the tutorial to better analyze them)

I'm not that familiar with them but you can maybe find something in the opencv docs or code

**Comment by lukasalexanderweber** [comment]
If you have updates on this please feel free to share them
