### ISSUE TITLE
StitchingError("No match exceeds the " "given confidence threshold.")

### ISSUE THREAD

**Issue by jayepep** [OpenStitching/stitching#78]
When I test with several images, I always have this problem: when I stitch four images, I only succeed in stitching img2 and img3. I have four images that overlap, so why can't I stitch them all?

Also, when I stitch img1 and img2, or img3 and img4, the following problem occurs:
`stitching.stitching_error.StitchingError: No match exceeds the given confidence threshold.`
Seeing as you mentioned setting the confidence_threshold lower or to 0 in the other solution, this is what happens next:
`cv2.error: OpenCV(4.7.0) /io/opencv/modules/calib3d/src/compat_ptsetreg.cpp:125: error: (-215:Assertion failed) !err.empty() in function ' update'`
For example, using img3.jpg and img4.jpg in my images gives the above situation.
I hope I can get your help and, in the future, how much overlap area should I ensure when doing stitching?

[There are my images:](https://drive.google.com/drive/folders/1bTa0NjlLrzeWSkmZWl66jee_hsVhlGt3?usp=sharing)

**Comment by lukasalexanderweber** [comment]
You need to stand still when you take the pictured. Apparently you moved to the left for at least the last image
